interface ImportMetaEnv {
  BASE_URL: string;
  VITE_APPWRITE_ENDPOINT: string;
  VITE_APPWRITE_PROJECT_ID: string;
  VITE_DATABASE_ID: string;
  VITE_PHOTOS_COLLECTION_ID: string;
  VITE_VOTES_COLLECTION_ID: string;
  VITE_PHOTO_APPEARANCE_COUNT_COLLECTION_ID: string;
  VITE_NUMBER_OF_PHOTOS: number;
}
